### ISSUE TITLE
Is 42 the answer here?

### ISSUE THREAD

**Issue by stephane-caron** [stack-of-tasks/state-observation#17]
For some reason I'm getting segmentation faults at the following line:

https://github.com/stack-of-tasks/state-observation/blob/38f8dd07fb69b18fd98858f094552d9ca75966b8/src/model-base-ekf-flex-estimator-imu.cpp#L363

Shouldn't the ``42`` here be replaced by ``IMUElasticLocalFrameDynamicalSystem::input::contacts``, whose value is currently ``48``?

**Comment by proyan** [comment]
Irrespective of the question in the description, kudos for the Hitchhiker's guide reference. :trollface: #42IsAlwaysTheAnswer

**Comment by stephane-caron** [comment]
@proyan it's a biased kind of debugging :wink: 

Actually, it seems the "input" and "measurement input" are not the same thing, so 48 is not the answer either above. For now I fail to see why, but at any rate the `segment<3>(42 + 12*i)` of the input vector is not initialized in my case.

**Comment by stephane-caron** [comment]
OK got it, problem was popping from elsewhere... My apologies for the noise here :sweat_smile:

**Comment by olivier-stasse** [comment]
So 42 is still the answer...
